#!/usr/bin/env python3
from time import sleep

import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish

import config as MQTT_CONFIG


def on_publish(client, userdata, mid):
    print(f"Published(id={mid})")


client = mqtt.Client()
client.on_publish = on_publish
client.on_log = True

if MQTT_CONFIG.user:
    client.username_pw_set(MQTT_CONFIG.user, password=MQTT_CONFIG.password)
client.connect(MQTT_CONFIG.host, MQTT_CONFIG.port)

info = client.publish("imu", payload="sender: mqtt_pub.py")
info.wait_for_publish()
