#!/usr/bin/env bash -eu

SERIAL_PORT=/dev/tty.SLAB_USBtoUART
if [ ! -e $SERIAL_PORT ]; then
    echo "No device on port ${SERIAL_PORT}" 1>&2
    exit 1
fi

poetry run rshell -p $SERIAL_PORT rsync pyboard /pyboard
poetry run rshell -p $SERIAL_PORT repl \~ 'machine.reset()' \~
